# Generated by Django 6.1.1 on 2026-09-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='proces',
            new_name='procces',
        ),
        migrations.AlterField(
            model_name='process',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='forms.category'),
        ),
    ]
