# Generated by Django 6.1.1 on 2026-09-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_proces_form_procces_alter_process_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_requierd',
            new_name='is_required',
        ),
    ]
