# Generated by Django 6.1.1 on 2026-09-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_is_requierd_question_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('number', 'Number'), ('checkbox', 'Chehckbox')], default='text', max_length=30),
        ),
    ]
