# Generated by Django 6.1.1 on 2026-09-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
