# Generated by Django 6.1.1 on 2026-09-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_process_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="process",
            new_name="process",
        ),
    ]
