# Generated by Django 6.1.1 on 2026-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_process_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='views',
        ),
        migrations.AddField(
            model_name='form',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='form',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
