# Generated by Django 6.1.1 on 2026-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_process_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='views',
        ),
        migrations.AddField(
            model_name='form',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
